[package]
name = "aoc_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.13.0"
num-integer = "0.1.46"
rayon = "1.10.0"
proctor = { path = "../proctor" }
