use crate::utils;
use proctor::timed;

// Stub generated by Elf
pub fn solve() {
    let lines = utils::file_to_lines("{{year}}", "{{day}}");
    part_one(&lines);
    part_two(&lines);
}

#[timed]
fn part_one(lines: &[String]) -> usize {
    0
}

#[timed]
fn part_two(lines: &[String]) -> usize {
    0
}
